server:
  port: 8030
  servlet:
    context-path: '/api/v1'
spring:
  application:
    name: "nuam"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "00000"
  jpa:
    hibernate:
    ddl-auto: update
    datasource:
  hikari:
    minimum-idle: 5
    maximum-pool-size: 10